---
layout: default
bibliography: ref/ref15.bib
reference-location: document
title: Unattainable AGI and why it is not here
---

For a long time, there exists the debate on whether the world is approaching the fundamental point of "Singularity", as per the creation of an artificial general intelligence (AGI) in various forms, both in popular social phenomena and in research society. Just how much is this true? 

> The research is in progress, so don't ask me why (草)

### Summary

Large Language Model, or LLM ([@vaswani2017attention],[@devlin2019bert],[@brown2020language],[@zhao2023llmsurvey],[@zhao2024llmsurvey2],[@radford2019language],[@radford2018improving],[@raffel2020exploring],[@touvron2023llama],[@touvron2023llama2],[@chowdhery2022palm],[@ouyang2022training],[@wei2022chain],[@kaplan2020scaling],[@hoffmann2022training],[@bai2022constitutional]) is one of the most successful, most advanced, and most developed type of model in the current modern machine learning landscape, and of AI (Artificial Intelligence) research at large. Its success has not been lacking, and its reputation and widespread uses have been proved over time. The effect of LLM has been realized, and indeed has been changing the landscape of society in a very much difficult way. Latest model of such architecture, like [@openai_gpt5_2025],[@wang2025capabilitiesgpt5multimodalmedical],[@openai_inside_gpt5_2025]'s GPT-5, [@guo_deepseek_r1_2025],[@deepseek_hf_2025]'s DeepSeek AI, [@anthropic_claude3_modelcard_2024],[@anthropic_tracing_thoughts_2025]'s Claude AI, [@touvron_llama_2023]'s LLaMA, [@chowdhery_palm_2022],[@anil_palm2_2023]'s *PaLM / PaLM-2*, and [@jiang_mistral7b_2023],[@mistral_blog_2023]'s Mistral (Mistral-7B), pushed this boundary further and further, and levelling up many tasks and purposes with AI system in practice, and further onward with techniques like [@wei2022chain]'s *Chain-of-Thought prompting*, [@kaplan2020scaling]'s scaling law, and more ([@hoffmann2022training],[@bai2022constitutional]).

However, with such development, come great expectation, great speculation, and also great hallucination. New development of the field of AI even earlier than \cite{vaswani2017attention} paper on the Transformer neural network which fuelled the revolution of AI exposure, has gathered a group of people speculated about the further exponential growth of AI, almost to a degree of religious, about the topic of a *Singularity*, where AI will become **Artificial General Intelligence** (AGI). This is reflected in popular culture phenomena, speculation, researches, interpretation of reasoning behaviours and so on, for example, in [@barrat_our_final_invention_2013],[@birch_edge_of_sentience_2024],[@yudkowsky_soares_anyone_builds_2025],[@hao_empire_of_ai_2025],[@bostrom_superintelligence_2014], and more broadly on LLM in specific, [@mumuni_survey_llms_for_agi_2025],[@shang_ai_native_memory_2024],[@llm_cognitive_capabilities_evidence_2024],[@goertzel_generative_ai_vs_agi_2023],[@feng2024how],[@llms_assessment_for_singularity_2025] and [@cui_risk_taxonomy_mitigation_2024]. The claim is clear - we are pushing toward the age of AGI, and perhaps sooner or later, reach the state of Artificial Superintelligence (ASI) of which cited in popular culture as the cultivation point of the Singularity - the shift of society toward a society of abundance, post-scarcity state. Most proponents point to LLM for such advancement, as it is one of the most widespread success and accessible form of interaction with AI systems on large scale. Pushbacks against such movement, including such as [@friedman2024inference],[@lesswrong2024parrot],[@bender2021dangers],[@baan2021slodderwetenschap],[@towardsai2023parrots] on the "Stochastic Parrot Hypothesis", [@njii2024agi] questioned of LLM path to AGI, the reverend [@alignmentforum2025] post itself, [@limgen2024],[@limitgen2025] on generating suggestive limitation of research paper, [@cacm2025knockout],[@marcus2023elegant]'s' critique on generative AI on world models and failure of LLM, @llm2024primer on limitation of LLM, similarly [@zhang2025lllms], mathematics critique in [@mirzadeh2024gsm], and more. However, the generally public, and more so of the positivity of the inner market on AI focus on the development and increment of larger models toward such goal. It is not too offset to hear the phrase "AGI will be in $X$ days/month/year", as much as it is a social phenomena even in small or large circle. Objectively, such positivity is not without basis. Furthermore, it is rather with certain amount of irony that the research made use of AI itself, for reference taking purposes. 

Nevertheless, a critical task can be given out of such argument and thorough development of the current debate. What can then be extrapolated from the ongoing dilemma? What has to do with the architecture, the consideration about AGI that is now turned into the debate of will LLM be AGI? How is our understanding of the concept of AI, AGI, and ASI in general? And of a sense, what will provide us a pathway toward such goal?  